##################################################################################
#####                                TODO                                    #####
##################################################################################
Todo:
  path: webservice/todo/
  properties:
    id:
      required: true
      type: int
    title:
      required: true
      type: String
    completed:
      required: true
      type: bool
